services:
    ubuntu:
        build:
            context: .
            dockerfile: ./Dockerfile
        privileged: true
        volumes:
            - .:/home/app
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        command: bash -c "sleep infinity"
